# Generated by Django 4.2.17 on 2025-01-04 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('trade', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('rate', models.FloatField()),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=50, unique=True)),
                ('total_buy', models.IntegerField(default=0)),
                ('avg_buy', models.FloatField(default=0)),
                ('total_sell', models.IntegerField(default=0)),
                ('avg_sell', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
            ],
        ),
    ]
